name: amap_location
description: A Flutter plugin to use amap location.高德地图定位组件
version: 0.1.0
author: JZoom<jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_amap_location

dependencies:
  flutter:
    sdk: flutter
  simple_permissions:
  easy_alert:

environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

flutter:
  plugin:
    androidPackage: com.jzoom.amaplocation
    pluginClass: AmapLocationPlugin